name: WHen PR opened do this

on: 
 pull_request:
   types:
     - "opened"

jobs:
  Run_the_thing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
       clean: true
       fetch-depth: 0
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Run a command
      run: |
        $Question = "Who Opened PR {0} titled {1}?" -f '${{ github.event.pull_request.number }}' , '${{ github.event.pull_request.title }}' 
        $Answer = "{3} Opened PR {0} titled {1}?" -f '${{ github.event.pull_request.number }}' , '${{ github.event.pull_request.title }}' , '${{ github.event.pull_request.user.login }}' 
        
        Write-Host $Question 
        Write-Host $Answer
      shell: pwsh
      continue-on-error: true   
